Lost password reset
blindnet-io/product-management pull request #542
Opened 2022-04-20 13:26 UTC by Clementinev

Create 01-DR-Lost-password-reset

2022-07-12 19:27 UTC, milstan requested changes

2022-07-12 19:29 UTC, milstan commented
I am taking over the vlaidation process for this PR.

@Clementinev do you still want this merged? If so, please resolve comments that you've integrated, or explain further if needed.

If no objections is made, I'll merge this.

2022-07-19 09:15 UTC, milstan commented
@Clementinev do you still want this merged?

2022-07-20 09:42 UTC, Clementinev commented
Yes, I made the needed updates

2022-07-20 09:48 UTC, milstan approved these changes

2022-07-20 09:49 UTC, merged