Conceptualization updates
blindnet-io/product-management pull request #634
Opened 2022-05-17 08:18 UTC by milstan

Seveal updates reflecting our recent discussions. Please review.

2022-05-30 23:46 UTC, milstan commented
ping @m4rk055 could you pelase review this?

2022-05-31 12:06 UTC, m4rk055 requested changes

2022-05-31 12:06 UTC, m4rk055 commented on refs/high-level-conceptualization/README.md
> +- **Modifications** by Data Consumers and DPOs (when the new data is collected offline from the Data Subject)
Also modifications BY data subjects not related to a rights request, if the access to data is provided through the UI (changing the phone number on a user's profile page, request for additional data by data consumer, etc.).

2022-06-02 10:03 UTC, noelmace commented on refs/high-level-conceptualization/README.md
> +See [Bridge Pattern, Gang of Four](https://refactoring.guru/design-patterns/bridge).
Alternative (approximative) proposal: "we recommend following the Bridge Pattern when implementing such a system"
Depending on what @milstan had in mind here.

2022-06-02 10:03 UTC, noelmace commented on refs/high-level-conceptualization/README.md
> +- **a posteriori** using human input to vlaidate the conformity of submitted data with what is expected
```suggestion
- **a posteriori** using human input to validate the conformity of submitted data with what is expected
```

2022-06-02 12:54 UTC, milstan commented on refs/high-level-conceptualization/README.md
> +- **Modifications** by Data Consumers and DPOs (when the new data is collected offline from the Data Subject)
```suggestion
- **Modifications** by Data Consumers (e.g., within modificaiton requests, or through common featues for user profile modification, or any other way) and DPOs (when the new data is collected offline from the Data Subject)
```

2022-06-02 12:56 UTC, milstan commented
I've addressed the change. @noelmace feel free to do final revision and merge if OK.

2022-06-07 18:49 UTC, milstan commented on refs/high-level-conceptualization/README.md
> +
```suggestion
Composition of the components of the system is inspired by the bridge design pattern.
```

2022-06-07 18:49 UTC, milstan commented on refs/high-level-conceptualization/README.md
> +See [Bridge Pattern, Gang of Four](https://refactoring.guru/design-patterns/bridge).
done

2022-06-07 18:51 UTC, milstan commented on refs/high-level-conceptualization/README.md
> +- **Modifications** by Data Consumers and DPOs (when the new data is collected offline from the Data Subject)
```suggestion
- **Modifications** by Data Consumers and DPOs (when the new data is collected offline from the Data Subject, or a modification directly made by the Data Subject through a user interface).
```

2022-06-07 18:53 UTC, milstan commented on refs/high-level-conceptualization/README.md
> +- **Modifications** by Data Consumers and DPOs (when the new data is collected offline from the Data Subject)
```suggestion
- **Modifications** by Data Subjects (directly throught user interface) or by Data Consumers and DPOs (when the new data is collected offline from the Data Subject)
```

2022-06-07 18:54 UTC, milstan commented
changes made. @m4rk055 see if OK and @noelmace please merge

2022-06-09 10:51 UTC, m4rk055 approved these changes

2022-06-09 11:26 UTC, milstan commented
@noelmace please merge now. I need this for other updates

2022-06-09 13:14 UTC, merged