Add Form validation update in Product-design-choices.md
blindnet-io/product-management pull request #797
Opened 2022-07-11 13:33 UTC by Clementinev

Added Form validation update from https://github.com/blindnet-io/product-management/issues/303 in Product-design-choices.md document

2022-07-11 13:50 UTC, m4rk055 approved these changes

2022-07-11 14:03 UTC, milstan requested changes

2022-07-11 14:03 UTC, milstan commented on refs/Product-design-choices.md
> +*Error message should be under the field rather than in the right panel tooltip
```suggestion

```
Same as above

2022-07-12 19:17 UTC, milstan approved these changes

2022-07-12 19:22 UTC, milstan commented
@Clementinev According to the [DR0002](https://github.com/blindnet-io/openness-framework/blob/main/docs/decision-records/DR-0002-dr-validation.md) if you want things to move faster on this kind of requests, you MUST assign someone, in this particular case, you SHOULD aisng me.

If you only ask me for a review, I'll just do that. Nothing more. It is by pure chance that I looked here to see who was the Assignee, and I saw nobody.

2022-07-12 19:23 UTC, milstan commented
Very good initiative to have this at a deisng choice level. Thanx @Clementinev

2022-07-12 19:23 UTC, merged